"""Shareable SVG artifacts: an embeddable grade badge and a social share card.

Small businesses and agencies share a result, not a JSON file. The badge is
meant for a website footer ("scanned by SentinelDeck — Grade A"); the card is a
1200x630 image sized for link previews on X, LinkedIn, and Slack.
"""
from __future__ import annotations

from html import escape
from pathlib import Path

from sentineldeck.models import ScanReport

GRADE_COLORS = {
    "A": "#22c55e",
    "B": "#84cc16",
    "C": "#f59e0b",
    "D": "#f97316",
    "F": "#ef4444",
}
DEFAULT_GRADE_COLOR = "#64748b"
SEVERITY_ORDER = ("critical", "high", "medium", "low", "info")


def grade_color(grade: str) -> str:
    return GRADE_COLORS.get(grade.upper(), DEFAULT_GRADE_COLOR)


def _severity_counts(report: ScanReport) -> dict[str, int]:
    counts = {severity: 0 for severity in SEVERITY_ORDER}
    for finding in report.findings:
        severity = finding.severity.lower()
        counts[severity if severity in counts else "info"] += 1
    return counts


def _text_width(text: str, char_px: float) -> float:
    # Rough average glyph width; good enough to keep a shields-style badge tidy.
    return len(text) * char_px


def render_badge_svg(report: ScanReport) -> str:
    """A compact, shields-style badge: ``SentinelDeck | Grade A``."""
    label = "SentinelDeck"
    value = f"Grade {escape(report.grade)}"
    color = grade_color(report.grade)

    label_w = int(_text_width(label, 6.6)) + 16
    value_w = int(_text_width(value, 6.6)) + 16
    total_w = label_w + value_w
    label_mid = label_w / 2
    value_mid = label_w + value_w / 2

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="{total_w}" height="20" role="img" aria-label="SentinelDeck grade {escape(report.grade)}">
  <linearGradient id="s" x2="0" y2="100%">
    <stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
    <stop offset="1" stop-opacity=".1"/>
  </linearGradient>
  <rect rx="3" width="{total_w}" height="20" fill="#1f2937"/>
  <rect rx="3" x="{label_w}" width="{value_w}" height="20" fill="{color}"/>
  <rect rx="3" width="{total_w}" height="20" fill="url(#s)"/>
  <g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
    <text x="{label_mid:.0f}" y="14">{escape(label)}</text>
    <text x="{value_mid:.0f}" y="14" font-weight="bold">{value}</text>
  </g>
</svg>
"""


def render_card_svg(report: ScanReport) -> str:
    """A 1200x630 social share card summarising the scan."""
    counts = _severity_counts(report)
    color = grade_color(report.grade)
    target = escape(report.target)
    high_total = counts["critical"] + counts["high"]

    stats = [
        ("Risk score", f"{report.risk_score}/100"),
        ("Findings", str(len(report.findings))),
        ("High / Critical", str(high_total)),
        ("Medium", str(counts["medium"])),
    ]
    stat_cells = "".join(
        f"""
      <g transform="translate({80 + i * 270},430)">
        <rect width="240" height="120" rx="18" fill="#101c2f" stroke="#1e3a5f"/>
        <text x="24" y="46" fill="#9fb3c8" font-size="20" font-family="Inter,sans-serif">{escape(label)}</text>
        <text x="24" y="92" fill="#edf5ff" font-size="40" font-weight="700" font-family="Inter,sans-serif">{escape(value)}</text>
      </g>"""
        for i, (label, value) in enumerate(stats)
    )

    return f"""<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630" viewBox="0 0 1200 630" role="img" aria-label="SentinelDeck report for {target}">
  <defs>
    <radialGradient id="bg" cx="20%" cy="0%" r="90%">
      <stop offset="0" stop-color="#12345c"/>
      <stop offset="0.45" stop-color="#08111f"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#bg)"/>
  <text x="80" y="110" fill="#38bdf8" font-size="22" letter-spacing="4" font-family="Inter,sans-serif" font-weight="700">SENTINELDECK SECURITY REPORT</text>
  <text x="80" y="200" fill="#edf5ff" font-size="72" font-weight="800" font-family="Inter,sans-serif">{target}</text>
  <text x="80" y="250" fill="#9fb3c8" font-size="24" font-family="Inter,sans-serif">Passive attack-surface posture</text>
  <g transform="translate(940,90)">
    <circle cx="90" cy="90" r="90" fill="#101c2f" stroke="{color}" stroke-width="8"/>
    <text x="90" y="80" fill="{color}" font-size="96" font-weight="800" text-anchor="middle" font-family="Inter,sans-serif">{escape(report.grade)}</text>
    <text x="90" y="135" fill="#9fb3c8" font-size="22" text-anchor="middle" font-family="Inter,sans-serif">Grade</text>
  </g>
  {stat_cells}
  <text x="80" y="600" fill="#64748b" font-size="20" font-family="Inter,sans-serif">Generated by SentinelDeck — passive attack-surface visibility for small businesses.</text>
</svg>
"""


def write_badge_svg(report: ScanReport, output: str | Path) -> Path:
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_badge_svg(report), encoding="utf-8")
    return path


def write_card_svg(report: ScanReport, output: str | Path) -> Path:
    path = Path(output)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_card_svg(report), encoding="utf-8")
    return path
